---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: my-blue-build-sway-os
# description will be included in the image's metadata
description: This is my personal OS image.
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
       # install fsearch nightly; the non-nighly version in COPR has dependency errors during installation (also experienced by other users)
      - https://copr.fedorainfracloud.org/coprs/cboxdoerfer/fsearch_nightly/repo/fedora-%OS_VERSION%/cboxdoerfer-fsearch_nightly-fedora-%OS_VERSION%.repo
    install:
      - starship
      - fsearch

  - type: rpm-ostree
    install:
      - emacs
      - nnn
      - fzf
      - ripgrep
      - fd-find
      - bfs
      - NetworkManager-tui
      - syncthing
      - tldr # help/cheet sheets
      - flameshot # screenshot
      - fastfetch # system info
    remove:
      # "firefox" is the main package, "firefox-langpacks" is a dependency; remove firefox-langs first then firefox, otherwise build throws error
      - firefox-langpacks
      - firefox

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - org.mozilla.firefox
        - org.goldendict.GoldenDict
        - org.kde.okular
        - org.mozilla.Thunderbird
        - org.zotero.Zotero
        - net.ankiweb.Anki
        - org.keepassxc.KeePassXC
        - org.signal.Signal
        - us.zoom.Zoom
      # remove:
      #   - org.gnome.eog
    # user: {} # Also add Flathub user repo, but no user packages
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  # install homebrew
  - type: brew
    brew-analytics: false # disable telemetry
